name: ci-golang-workflow
#https://docs.github.com/pt/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on: 
  pull_request: 
    branches:
      - develop
jobs:
  ckeck-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.15']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}
      - run: go test
      - run: go run math.go